# Generated by Django 5.1.1 on 2024-11-30 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babyaccountsapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="accountingentry",
            name="business",
        ),
        migrations.RemoveField(
            model_name="accountingentry",
            name="head",
        ),
        migrations.RemoveField(
            model_name="accountingentry",
            name="ledger",
        ),
        migrations.RemoveField(
            model_name="accountingentry",
            name="mode",
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="babyaccountsapp.customer",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Business",
        ),
        migrations.DeleteModel(
            name="Head",
        ),
        migrations.DeleteModel(
            name="Ledger",
        ),
        migrations.DeleteModel(
            name="AccountingEntry",
        ),
        migrations.DeleteModel(
            name="Mode",
        ),
    ]
