# Generated by Django 5.1.1 on 2024-11-30 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "babyaccountsapp",
            "0003_business_ledger_mode_remove_transaction_customer_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Accounting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "cr",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "dr",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "gst",
                    models.CharField(
                        choices=[
                            ("with_gst", "With GST"),
                            ("without_gst", "Without GST"),
                        ],
                        default="with_gst",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="babyaccountsapp.business",
                    ),
                ),
                (
                    "ledger",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="babyaccountsapp.ledger",
                    ),
                ),
                (
                    "mode",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="babyaccountsapp.mode",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
