# Generated by Django 5.1.1 on 2024-11-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("babyaccountsapp", "0004_accounting_delete_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ledger",
            name="mode",
        ),
    ]
