# Generated by Django 5.1.1 on 2024-11-30 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babyaccountsapp", "0005_remove_ledger_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Head",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("head_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="ledger",
            name="ledger_head",
        ),
        migrations.AddField(
            model_name="accounting",
            name="head",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="babyaccountsapp.head",
            ),
        ),
    ]
