# Generated by Django 5.1.1 on 2024-11-30 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babyaccountsapp", "0006_head_remove_ledger_ledger_head_accounting_head"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="head",
            name="head_type",
        ),
        migrations.AddField(
            model_name="head",
            name="name",
            field=models.CharField(default="Default Head", max_length=255),
        ),
        migrations.AlterField(
            model_name="accounting",
            name="head",
            field=models.ForeignKey(
                default="Default Head",
                on_delete=django.db.models.deletion.CASCADE,
                to="babyaccountsapp.head",
            ),
        ),
    ]
