# Generated by Django 5.1.1 on 2024-11-30 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babyaccountsapp", "0007_remove_head_head_type_head_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounting",
            name="head",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="babyaccountsapp.head",
            ),
        ),
    ]
