services:
  - type: web
    name: babyaccounts
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ALLOWED_HOSTS
        value: "babyaccounts.onrender.com,.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://babyaccounts-ptc66lakw-sumothewrestlers-projects.vercel.app"